### ISSUE TITLE
'wmic' command throwing access denied in azure app service

### ISSUE THREAD

**Issue by joejoseph10jj** [sindresorhus/windows-release#10]
I am trying to get the archive link from my node js application.This is working fine in my local machine but i am getting error in azure private app service.

octokit.repos.getArchiveLink({owner:owner,repo:sourceRepoName,archive_format:'zipball',ref:branch}) on executing this command in azure private app service I am getting the following error

{ Error: Command failed: wmic os get Caption
Access is denied.
at makeError (D:\home\site\wwwroot\node_modules\execa\index.js:172:9)
at Function.module.exports.sync (D:\home\site\wwwroot\node_modules\execa\index.js:341:15)
at module.exports.release (D:\home\site\wwwroot\node_modules\windows-release\index.js:34:24)
at module.exports (D:\home\site\wwwroot\node_modules\os-name\index.js:39:18)
at getUserAgentNode (D:\home\site\wwwroot\node_modules\universal-user-agent\index.js:6:51)
at restEndpoint (D:\home\site\wwwroot\node_modules@octokit\rest\lib\endpoint\index.js:27:48)
at restRequest (D:\home\site\wwwroot\node_modules@octokit\rest\lib\request\index.js:7:26)
code: 1,
stdout: '',
stderr: 'Access is denied.\r\n',
failed: true,
signal: null,
cmd: 'wmic os get Caption',
timedOut: false }

So on diving deep into the error I noticed that the wmic command in this package is throwing this error.
I contacted with azure team and they said that windows commands execution is denied in azure app service.
Can you provide any alternative for this as this was working fine when I was using your earlier module 'win-release'.

**Comment by cliffkoh** [comment]
+1, hit this too..

**Comment by sindresorhus** [comment]
// @MarkTiedemann In case you would want to whip up a Windows binary for this. Would probably be much faster than `wmic` too.

**Comment by MarkTiedemann** [comment]
@sindresorhus `wmic` is only used to distinguish between desktop Windows and Windows Server, right? If so, I could put [IsWindowsServer](https://docs.microsoft.com/en-us/windows/desktop/api/VersionHelpers/nf-versionhelpers-iswindowsserver) into a binary.

A mapping of Windows versions and Server years can be found [here](https://docs.microsoft.com/en-us/windows/desktop/api/winnt/ns-winnt-_osversioninfoexa#remarks):

version | year
--- | ---
5.2 | 2003
6.0 | 2008
6.1 | 2008
6.2 | 2012
6.3 | 2012
10.0 | 2016

**Comment by MarkTiedemann** [comment]
@sindresorhus [`is-windows-server`](https://github.com/MarkTiedemann/is-windows-server) is done. Let me know if you need anything else. :)
