### ISSUE TITLE
[BUG] Crash on Windows 11 with `TypeError: execa.sync is not a function`

### ISSUE THREAD

**Issue by nichita-rusin** [sindresorhus/windows-release#33]
## Environment
* OS: Windiws 11 Pro 23H2
* node: 20.14.0
* npm: 10.7.0
* windows-release: 6.0.0

## Description
Calling `windowsRelease()` throws an error:
```shell
$ node index.js
file:///C:/flow/node_modules/windows-release/index.js:42
                        stdout = execa.sync('powershell', ['(Get-CimInstance -ClassName Win32_OperatingSystem).caption']).stdout || '';
                                       ^

TypeError: execa.sync is not a function
    at windowsRelease (file:///C:/flow/node_modules/windows-release/index.js:42:19)
    at file:///C:/flow/index.js:3:13
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.14.0
error Command failed with exit code 1.
```

## Cause
`execa` release v6.0.0 included a [breaking change](https://github.com/sindresorhus/execa/releases/tag/v6.0.0) that removed the `execa.sync` function. When `windows-release` was upgraded to v6, the code [was not modified](https://github.com/sindresorhus/windows-release/commit/5fc9b20a36ffeafb4413ed51b0e035657f155492#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R43) to reflect this change.

**Comment by nichita-rusin** [comment]
Fixing this in PR #34
